"""empty message

Revision ID: 12fb5b250c20
Revises: 798d6deffc32
Create Date: 2020-12-22 18:58:56.303341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12fb5b250c20'
down_revision = '798d6deffc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('divvy', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=55),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('divvy', 'birthday',
               existing_type=sa.String(length=55),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
