"""empty message

Revision ID: 798d6deffc32
Revises: 
Create Date: 2020-12-22 18:43:09.354378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798d6deffc32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('stoptime', sa.DateTime(), nullable=True),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_name', sa.String(length=55), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(length=55), nullable=True),
    sa.Column('usertype', sa.String(length=55), nullable=True),
    sa.Column('gender', sa.String(length=55), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divvy')
    # ### end Alembic commands ###
